import Head from "next/head";
import { GetStaticProps } from "next";
export default function Home({ repositories, date }) {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>{date}</h1>
        <ul>
          {repositories.map((repo) => (
            <li key={repo}>{repo}</li>
          ))}
        </ul>
      </main>
    </div>
  );
}

export const getStaticProps: GetStaticProps = async () => {
  const response = await fetch("https://api.github.com/users/jeandeson/repos");
  const data = await response.json();
  const repositoriesNames = data.map((item) => item.name);
  return {
    props: {
      repositories: repositoriesNames,
      date: new Date().toISOString(),
    },
    revalidate: 60 * 60 * 4,
  };
};
